export const config = {
  fonts: {
    font900: 'Roboto-Black',
    font900Italic: 'Roboto-BlackItalic',
    font700: 'Roboto-Bold',
    font700Italic: 'Roboto-BoldItalic',
    font500: 'Roboto-Medium',
    font500Italic: 'Roboto-MediumItalic',
    font400: 'Roboto-Regular',
    font400Italic: 'Roboto-Regular',
    font300: 'Roboto-Light',
    font300Italic: 'Roboto-LightItalic',
  },
  spacings: {
    xs: 4,
    s: 8,
    m: 12,
    l: 16,
    xl: 20,
    '2xl': 24,
    '3xl': 28,
    '4xl': 32,
    '5xl': 36,
  },
  textVariants: {
    default: {},
    body: {
      fontSize: 16,
      lineHeight: 24,
    },
    'text-xs': {
      fontSize: 12,
    },
    'text-sm': {},
    'text-base': {},
    'text-lg': {},
    'text-xl': {},
    'text-2xl': {},
    'text-3xl': {},
    'text-4xl': {},
    'text-5xl': {},
  },
};
